// Generated by gencpp from file opencv_node/vision_msg.msg
// DO NOT EDIT!


#ifndef OPENCV_NODE_MESSAGE_VISION_MSG_H
#define OPENCV_NODE_MESSAGE_VISION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <opencv_node/object.h>

namespace opencv_node
{
template <class ContainerAllocator>
struct vision_msg_
{
  typedef vision_msg_<ContainerAllocator> Type;

  vision_msg_()
    : objects()  {
    }
  vision_msg_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::opencv_node::object_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::opencv_node::object_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;




  typedef boost::shared_ptr< ::opencv_node::vision_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opencv_node::vision_msg_<ContainerAllocator> const> ConstPtr;

}; // struct vision_msg_

typedef ::opencv_node::vision_msg_<std::allocator<void> > vision_msg;

typedef boost::shared_ptr< ::opencv_node::vision_msg > vision_msgPtr;
typedef boost::shared_ptr< ::opencv_node::vision_msg const> vision_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opencv_node::vision_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opencv_node::vision_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opencv_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'opencv_node': ['/home/pi/ieee-2019-electrical-software/Main-Program-2/src/opencv_node/msg', '/home/pi/ieee-2019-electrical-software/Main-Program-2/src/opencv_node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opencv_node::vision_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opencv_node::vision_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_node::vision_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opencv_node::vision_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_node::vision_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opencv_node::vision_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opencv_node::vision_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5abfddaa0c41b9448d210310355541e0";
  }

  static const char* value(const ::opencv_node::vision_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5abfddaa0c41b944ULL;
  static const uint64_t static_value2 = 0x8d210310355541e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::opencv_node::vision_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opencv_node/vision_msg";
  }

  static const char* value(const ::opencv_node::vision_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opencv_node::vision_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object[] objects\n\
================================================================================\n\
MSG: opencv_node/object\n\
uint32 x_position\n\
uint32 y_position\n\
uint32 width\n\
uint32 height\n\
float32 distance\n\
uint8 color_index\n\
uint8 object_type\n\
";
  }

  static const char* value(const ::opencv_node::vision_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opencv_node::vision_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vision_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opencv_node::vision_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opencv_node::vision_msg_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::opencv_node::object_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENCV_NODE_MESSAGE_VISION_MSG_H
