# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from opencv_node/vision_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import opencv_node.msg

class vision_msg(genpy.Message):
  _md5sum = "5abfddaa0c41b9448d210310355541e0"
  _type = "opencv_node/vision_msg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """object[] objects
================================================================================
MSG: opencv_node/object
uint32 x_position
uint32 y_position
uint32 width
uint32 height
float32 distance
uint8 color_index
uint8 object_type
"""
  __slots__ = ['objects']
  _slot_types = ['opencv_node/object[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       objects

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vision_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.objects is None:
        self.objects = []
    else:
      self.objects = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        _x = val1
        buff.write(_get_struct_4If2B().pack(_x.x_position, _x.y_position, _x.width, _x.height, _x.distance, _x.color_index, _x.object_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.objects is None:
        self.objects = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = opencv_node.msg.object()
        _x = val1
        start = end
        end += 22
        (_x.x_position, _x.y_position, _x.width, _x.height, _x.distance, _x.color_index, _x.object_type,) = _get_struct_4If2B().unpack(str[start:end])
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        _x = val1
        buff.write(_get_struct_4If2B().pack(_x.x_position, _x.y_position, _x.width, _x.height, _x.distance, _x.color_index, _x.object_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.objects is None:
        self.objects = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = opencv_node.msg.object()
        _x = val1
        start = end
        end += 22
        (_x.x_position, _x.y_position, _x.width, _x.height, _x.distance, _x.color_index, _x.object_type,) = _get_struct_4If2B().unpack(str[start:end])
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4If2B = None
def _get_struct_4If2B():
    global _struct_4If2B
    if _struct_4If2B is None:
        _struct_4If2B = struct.Struct("<4If2B")
    return _struct_4If2B
